### ISSUE TITLE
Active Model Errors

### ISSUE THREAD

**Issue by rafaltrojanowski** [robinbortlik/validates_overlap#42] opened 2017-05-25 19:30 UTC
Hey,

I'm wondering if this code:

```
  validates :start_at, :end_at, overlap: { ... }
```

shouldn't add errors for :start_at and :end_at? Actually it adds error only for :start_at. What do you think?

**Comment by robinbortlik** [comment] 2017-05-25 19:42
Hi, 

looking to the code, I can confirm, that error message is added to the first attribute only. 
https://github.com/robinbortlik/validates_overlap/blob/master/lib/validates_overlap/overlap_validator.rb#L27
What is the use case for you to have it on both attributes?
Wouldn't you have duplicated error messages?

**Comment by rafaltrojanowski** [comment] 2017-05-26 18:16
Thanks for your quick reply.

I think that it would be useful for someone who uses https://github.com/plataformatec/simple_form and would like to have displayed errors with both fields out of the box. I think that it's even more appropriate to show error for ended_at too in that case because gem doesn't provide information which attribute fails validation in fact, correct? In other words, if error is assigned to start_at only it may suggest that started_at overlaps, but it does not have to be true.

For apps which doesn't display errors inline that's not necessary. As you said, it would lead to duplicated errors. Ideally would be to allow to configure it somehow then, I think.

**Comment by rafaltrojanowski** [comment] 2017-06-01 20:10
@robinbortlik What do you think about #43 ?

**Comment by robinbortlik** [comment] 2017-06-02 05:26
Hi @rafaltrojanowski first, I would really like to apologise because I'm so busy with my daily job and forgot to answer you. 
So basically your solution adds error to multiple fields, but how do you know which one really overlapped? 
I'm definitely fine with this solution if it fulfil your needs. Or we can take it as a first step and think about how to make it even better later. 
So do you want me to merge it now? 
Will this solution really help you?

**Comment by robinbortlik** [comment] 2017-06-05 05:57
Closed by #43

**Closed by robinbortlik** 2017-06-05 05:57 UTC
