### ISSUE TITLE
Using ActiveRecord enum column in overlap scope option

### ISSUE THREAD

**Issue by simonasdev** [robinbortlik/validates_overlap#26] opened 2015-07-23 15:49 UTC
Hey @robinbortlik, just discovered a possible bug. It occurs, when one of the columns specified in the scope option is an ActiveRecord enum. Value from the model (which is a string/symbol) is not being converted to the corresponding integer, so SQL casts that string into integer, which will always be zero, so validations are invalid. Here is the setup code:

``` ruby
class ObjectParameterValue < ActiveRecord::Base
  enum kind: [:contract, :fact, :draft]

  validates :valid_from, :valid_until, overlap: { 
    exclude_edges: ['valid_from', 'valid_until'], 
    scope: ['object_parameter_id', 'resource_id', 'resource_type', 'kind']
  }
end
```

Here is the generated SQL, when `kind: :fact`

``` sql
SELECT  1 AS one FROM `object_parameter_values` 
WHERE ((object_parameter_values.valid_until IS NULL OR object_parameter_values.valid_until > '2002-11-05') 
AND (object_parameter_values.valid_from IS NULL OR object_parameter_values.valid_from < '2003-12-01') 
AND object_parameter_values.object_parameter_id  = 1 
AND object_parameter_values.resource_id  = 613 
AND object_parameter_values.resource_type  = 'Place' 
AND object_parameter_values.kind  = 'fact')
```

In the last line, you can see that condition is `object_parameter_values.kind  = 'fact'`, when it should be `object_parameter_values.kind  = 1`

There are none configuration options for this, so I suspect this must be a bug either in ActiveRecord itself, or somewhere in this library. What do you think?

**Comment by robinbortlik** [comment] 2015-07-23 17:57
Hello @simonasdev , 

first, thanks for nice report. I think you really found a bug. The tricky part is that when you ask enum attribute for value it will return you the value from array and not the value which comes to database. 

I will try to look on it. For now you can use a workaround that you will define some getter for kind method which will return you real king value. Something like this

``` ruby
def kind_value
  read_attribute(:kind)
end
```

and in you validation definition you will change ```kind``` to ```kind_value```

**Comment by robinbortlik** [comment] 2015-07-23 18:27
Ok, 

so I changed the ```send``` method to ```read_attribute``` if you will now set gem source from github then everything should start work with the validation definition as you had.

Let me please know if it helped

**Comment by robinbortlik** [comment] 2015-07-24 06:50
Try to update to 0.5.2 .

**Comment by simonasdev** [comment] 2015-07-24 10:02
I updated the Gemfile and it did start working, thanks a lot. This should be sufficient, since we can always use lambdas to overwrite the default `read_attribute`. Hopefully it didn't break anyone else's code.

**Comment by tejamedasani** [comment] 2016-12-20 16:41
Hi @robinbortlik, This bug fix is not working in Rails 5. `read_attribute` is returning values of enum after typecast. Only way i found to get the integer value is to use "read_attribute_before_typecast", but this breaks other columns like date. 
Currently, I am using the passing the following proc to scope in my model as a workaround. My enum is named day. 

`:scope => {"day" => proc{|object| object.class.days[object.day] } }`


As an aside, I am unable to declare procs when passing an array to the scope. 
For instance, this is not working
`:scope => ["attr1", attr2: => proc{|obj| obj.some_value}]`
This is the workaround i am using to use regular scope along with proc
`:scope => {"attr1" => 'false', attr2: => proc{|obj| obj.some_value}}`

Is this the expected behaviour? If yes, I think the readme needs to better reflect it. Let me know what you think and i will update the readme.

Code in the gem dealing with arrays and hashes in scope
` def add_attributes(record, attrs)`
   ` if attrs.is_a?(Array)`
     ` attrs.each { |attr| add_attribute(record, attr) }`
   ` elsif attrs.is_a?(Hash)`
      `attrs.each do |attr_name, value|`
       ` add_attribute(record, attr_name, value)`
    `  end`
    `else`
     ` add_attribute(record, attrs)`
   ` end`
 ` end`

**Comment by robinbortlik** [comment] 2016-12-20 17:13
Hi @tejamedasani I can take a look, but I' pretty busy at this moment, so it will not be earlier then next week or maybe week after. The PRs are always welcome.

**Comment by robinbortlik** [comment] 2017-01-02 18:40
Hi @tejamedasani the bug should be fixed by #38 . You can update gem version to `0.8.1` and everything should work.

**Closed by robinbortlik** 2017-01-02 18:40 UTC

**Comment by tejamedasani** [comment] 2017-01-03 04:17
Thanks Robin. 

Teja medasani

**Comment by Zmokizmoghi** [comment] 2017-11-14 09:23
Hello, @robinbortlik i'v just found this bug again.

```ruby
class Lession < ApplicationRecord
  enum day: {
    monday: 0,
    tuesday: 1,
    wednesday: 2,
    thursday: 3,
    friday: 4,
    saturday: 5,
    sunday: 6
  }
  validates :start_at, :end_at, overlap: { exclude_edges: ["starts_at", "ends_at"], scope: [:day]}
end
```
in that case function ```is_enum_attribute?``` will return false, because ```record.class.defined_enums[attr_name.to_s].present?``` return false.

But, if use ```  scope: ['day'] ``` methods above will return true.

Rails 5.1.4
validates_overlap at master@7be2f5e
 PR Attached
